apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite3
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: container34
          image: patillokesh/myimage
          ports:
            - containerPort: 4000
              protocol: TCP
